name: atypon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_login: ^4.2.0
  flutter_form_builder: ^9.1.0
  freezed: ^2.4.2
  flutter_riverpod: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.5
  riverpod_lint: ^2.0.0
  custom_lint: ^0.5.1

flutter:
  uses-material-design: true
